# This is a basic workflow to help you get started with Actions

name: Deploy to HostGator 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    timeout-minutes: 10
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    env:
      EMAIL: ${{ secrets.EMAIL }}
      BIKE_SITE: "bike-shop"
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install

      - name: Build master site
        run: |
          npm run deploy

      - name: Build sub-sites
        run: |
          cd $GITHUB_WORKSPACE${{ BIKE_SITE }} && ls -al
#          npm run deploy

      - name: SSH Setup
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Setup Git
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "nomad"
          echo git remote -v

      - name: Commit master
        run: |
          git add -A
          git commit -m "Commit changes to master branch"

      - name: Deploy to Hostgator
        run: |
          git remote add hostgator nomad@nomadmystic.com:public_html/static-sites
          git fetch --unshallow
          git push --force -u hostgator master

      - name: Debug
        run: |
          cd ~ && ls -al
          cd $GITHUB_WORKSPACE && ls -al
          cd $GITHUB_WORKSPACE && cd public && ls -al