# This is a basic workflow to help you get started with Actions

name: Deploy to HostGator 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    timeout-minutes: 10
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      EMAIL: ${{ secrets.EMAIL }}
      #      MACHINETOKEN: ${{ secrets.MACHINETOKEN }}
      #      PUUID: ${{ secrets.CHANGEME_PUUID }}
      #      SITENAME: ${{ secrets.CHANGEME_SITENAME }}
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm install
          npm run production --if-present

      - name: SSH Setup
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      #           ssh-keyscan -p 2222 appserver.dev.$PUUID.drush.in >> ~/.ssh/known_hosts

      - name: Setup Git
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "nomad"
          echo git remote -v

      - name: Deploy to Hostgator
        run: |
          git remote add hostgator nomad@nomadmystic.com:public_html/static-sites
          git fetch --unshallow
          git push --force -u hostgator master

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
